config/routes.rb
Rails.application.routes.draw do
  resources :figures
  resources :dances
  resources :categories
  resources :levels
  resources :routines
  resources :packages
  resources :payments
  resources :lessons
  resources :calendar
  resources :students
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "backup", to: "welcome#backup"
  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord

    def to_s
    return self.title
    end
end

app/models/dance.rb
class Dance < ApplicationRecord
  belongs_to :category
    def to_s
        return "#{self.category} #{self.title}"
    end
end

app/models/figure.rb
class Figure < ApplicationRecord
  belongs_to :level
  belongs_to :dance
  
  def to_s
    return self.title
  end
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :student
  has_one :package
  has_one :payment
  before_save :set_status
  validates :start_time, presence: true
  scope :this_years_lessons, -> { where('start_time > ?', Date.current.beginning_of_year) }
  
  def end_date
        self.start_time  + 60*60
  end
  
  def to_s
    self.student.last_name + " - " + self.start_time.to_formatted_s(:long)
  end
  
private
  def set_status
    if self.plan.present?
    self.is_planned = true
else
    self.is_planned = false
    end
    if self.payment_id || self.package_id
        self.is_paid = true
    else
        self.is_paid = false
    end
  end
end

app/models/level.rb
class Level < ApplicationRecord
    def to_s
        return self.title
    end
end

app/models/package.rb
class Package < ApplicationRecord
  belongs_to :student
  belongs_to :payment
  has_many :lessons, dependent: :destroy
  enum status: [ :active, :inactive ]
  after_find :set_activity
  
  def remaining
   return self.lessons_purchased - self.lessons.count
  end
  
  def to_s
   self.student.last_name + " payment with ID of #{self.payment_id} on " + self.payment.payment_date.strftime("%A, %b. %d") 
  end

    def set_activity
    if self.lessons_purchased > self.lessons.count
        self.active!
     else
         self.inactive!
    end
    end

end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :student
  

  def to_s  
    student.last_name + " payment of #{amount} on " + payment_date.strftime("%m/%d/%Y")
  end
  
end

app/models/routine.rb
class Routine < ApplicationRecord
  belongs_to :student
end

app/models/student.rb
class Student < ApplicationRecord
    has_many :packages
    has_many :routines
    def to_s
     return self.first_name + " " + self.last_name
    end
    
    def lessons_remaining
        @lessons = 0
        self.packages.each do |p|
            @lessons += p.remaining
        end
        return @lessons
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :set_lesson, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, :ensure_admin!
  
  # GET /lessons
  # GET /lessons.json
  def index
    @lessons = Lesson.all.order(start_time: :desc)
    # @lessons = Lesson.this_years_lessons.order(start_time: :desc)
    # Scope for weekly lessons. 
    respond_to do |format|
      format.html
    format.xlsx {
    response.headers['Content-Disposition'] = 'attachment; filename="all_lessons.xlsx"'
  }
    end
  end
  
  # GET /lessons/1
  # GET /lessons/1.json
  def show
  end

  # GET /lessons/new
  def new
    @lesson = Lesson.new()
    respond_to do |format|
    format.html
    format.js
    end
  end

  # GET /lessons/1/edit
  def edit
    @prevLesson= Lesson.where(:student_id => @lesson.student_id).where("start_time < ?", @lesson.start_time).last
    @payments = Payment.all
  end

  # POST /lessons
  # POST /lessons.json
  def create
    @lesson = Lesson.new(lesson_params)
    respond_to do |format|
      if @lesson.save
        format.html { redirect_to @lesson, notice: 'Lesson was successfully created.' }
        format.json { render :show, status: :created, location: @lesson }
      else
        format.html { render :new }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lessons/1
  # PATCH/PUT /lessons/1.json
  def update
    respond_to do |format|
      if @lesson.update(lesson_params)
        format.html { redirect_to @lesson, notice: 'Lesson was successfully updated.' }
        format.json { render :show, status: :ok, location: @lesson }
      else
        format.html { render :edit }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lessons/1
  # DELETE /lessons/1.json
  def destroy
    @lesson.destroy
    respond_to do |format|
      format.html { redirect_to lessons_url, notice: 'Lesson was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lesson
      @lesson = Lesson.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lesson_params
      params.require(:lesson).permit(:student_id, :start_time, :plan, :package_id, :payment_id, :recurring)
    end
end

app/helpers/calendar_helper.rb
module CalendarHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/dances_helper.rb
module DancesHelper
end

app/helpers/figures_helper.rb
module FiguresHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/levels_helper.rb
module LevelsHelper
end

app/helpers/packages_helper.rb
module PackagesHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/routines_helper.rb
module RoutinesHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/lessons/calendar.html.erb
<table class="ui celled table">
    <thead>
        <tr>
   <th>Sunday</th><th>Monday</th>
   <th>Tuesday</th><th>Wednesday</th>
   <th>Thursday</th><th>Friday</th>
   <th>Saturday</th>
  </tr>
  <tr>
  <% @beginning_of_month = Date.current.beginning_of_month %>
  <% @end_of_month = Date.current.end_of_month %>

<% (@beginning_of_month..@end_of_month).each do |d| %>
<% if d == @beginning_of_month %>
<% d.wday.times do %> <td class='offset'></td> <% end %>
<% end %>

<% if d.wday == 0 %> </tr><tr><% end %>
<td> <div class="datenum"><%= d.day %></div><br>
    <% Lesson.where(start_time: d.all_day).each do |l| %>
    <%= l.student.last_name %>
    <% end %>
</td>


<% end %>
</tr>
</table>

app/views/lessons/edit.html.erb
<h1>Editing Lesson</h1>

<%= render 'form', lesson: @lesson %>

<%= link_to 'Show', @lesson %> |
<%= link_to 'Back', lessons_path %>

app/views/lessons/index.html.erb
<h1 class="">Lessons</h1>
<a href="/calendar" class="ui button">Calendar</a>
<%= link_to 'New Lesson', new_lesson_path, class: "ui button" %>
<table class="ui unstackable sortable table">
  <thead>
    <tr>
      <th>Student</th>
      <th>Lesson Date</th>
      <th>Paid</th>
      <th>Planned</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lessons.each do |lesson| %>
      <tr>
        <td>
          <%= lesson.student.last_name %>
        </td>
        <td>
          <%= I18n.l lesson.start_time, format: :long %>
        </td>
        <td>
          <% if lesson.is_paid %><%= fa_icon "check" %><% end %>
        </td>
        <td>
          <% if lesson.is_planned %><%= fa_icon "check" %><% end %>
        </td>
        <td>
          <%= link_to 'Show', lesson %>
        </td>
        <td>
          <%= link_to 'Edit', edit_lesson_path(lesson) %>
        </td>
        <td>
          <%= link_to 'Destroy', lesson, method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
      <% end %>
  </tbody>
</table>  

<br>

<%= link_to 'Download as .xlsx', lessons_path(format: :xlsx) %>

app/views/lessons/index.pdf.erb
<!doctype html>
<html>
  <head>
    <meta charset='utf-8' />
    <%= wicked_pdf_stylesheet_link_tag "pdf" -%>
    <%= wicked_pdf_javascript_include_tag "number_pages" %>
  </head>
  <body onload='number_pages'>
    <div id="header">
    </div>
    <div id="content">
      <%= yield %>
      <h1 class="ui header">Lessons</h1>
<a href="/calendar" class="ui button">Calendar</a>
<%= link_to 'New Lesson', new_lesson_path, class: "ui button" %>
<table class="ui celled table">
  <thead>
    <tr>
      <th>Student</th>
      <th>Lesson Date</th>
      <th>Paid</th>
      <th>Planned</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lessons.each do |lesson| %>
      <tr>
        <td>
          <%= lesson.student.last_name %>
        </td>
        <td>
          <%= I18n.l lesson.lesson_date, format: :long %>
        </td>
        <td>
          <% if lesson.is_paid %><span class="ui centered">X</span><% end %>
        </td>
        <td>
          <% if lesson.is_planned %><span class="ui centered">X</span><% end %>
        </td>
        <td>
          <%= link_to 'Show', lesson %>
        </td>
        <td>
          <%= link_to 'Edit', edit_lesson_path(lesson) %>
        </td>
        <td>
          <%= link_to 'Destroy', lesson, method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
      <% end %>
  </tbody>
</table>
    </div>
  </body>
</html>

app/views/lessons/new.html.erb
<h1>New Lesson</h1>

<%= render 'form', lesson: @lesson %>

<%= link_to 'Back', lessons_path %>

app/views/lessons/show.html.erb
<div class="ui card fluid">
  <div class="content">
    <div class="header"><h2> <%= @lesson.student.first_name + ' ' + @lesson.student.last_name %></h2></div>
    <div class="meta"><h4><%= @lesson.start_time.strftime("%A, %b. %d - %I:%M%p") %></h4></div>
    <div class="description">
         <h2 class="centered">Plan</h2>
       <%= sanitize @lesson.plan %>
    </div>
  </div>
  <div class="extra content">
    <%= distance_of_time_in_words(@lesson.start_time, Time.now) %> <% if @lesson.start_time < Date.current %>ago.<% else %>until this lesson.<% end %>
     <p class="pull-right"><% if @lesson.is_paid %>Paid: <%= fa_icon 'check' %><% else %>Unpaid: <%= fa_icon 'times' %><% end %>
     <% if @lesson.is_planned %>Planned: <%= fa_icon 'check' %><% else %>Unplanned: <%= fa_icon 'times' %><% end %></p>
  </div>
</div>
<%= link_to 'Back', lessons_path %> |
<%= link_to 'Edit', edit_lesson_path(@lesson) %> |
<%= link_to 'Calendar', calendar_index_url %>