config/routes.rb
Rails.application.routes.draw do
  resources :figures
  resources :dances
  resources :categories
  resources :levels
  resources :routines
  resources :packages
  resources :payments
  resources :lessons
  resources :calendar
  resources :students
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "backup", to: "welcome#backup"
  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord

    def to_s
    return self.title
    end
end

app/models/dance.rb
class Dance < ApplicationRecord
  belongs_to :category
    def to_s
        return "#{self.category} #{self.title}"
    end
end

app/models/figure.rb
class Figure < ApplicationRecord
  belongs_to :level
  belongs_to :dance
  
  def to_s
    return self.title
  end
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :student
  has_one :package
  has_one :payment
  before_save :set_status
  validates :start_time, presence: true
  scope :this_years_lessons, -> { where('start_time > ?', Date.current.beginning_of_year) }
  
  def end_date
        self.start_time  + 60*60
  end
  
  def to_s
    self.student.last_name + " - " + self.start_time.to_formatted_s(:long)
  end
  
private
  def set_status
    if self.plan.present?
    self.is_planned = true
else
    self.is_planned = false
    end
    if self.payment_id || self.package_id
        self.is_paid = true
    else
        self.is_paid = false
    end
  end
end

app/models/level.rb
class Level < ApplicationRecord
    def to_s
        return self.title
    end
end

app/models/package.rb
class Package < ApplicationRecord
  belongs_to :student
  belongs_to :payment
  has_many :lessons, dependent: :destroy
  enum status: [ :active, :inactive ]
  after_find :set_activity
  
  def remaining
   return self.lessons_purchased - self.lessons.count
  end
  
  def to_s
   self.student.last_name + " payment with ID of #{self.payment_id} on " + self.payment.payment_date.strftime("%A, %b. %d") 
  end

    def set_activity
    if self.lessons_purchased > self.lessons.count
        self.active!
     else
         self.inactive!
    end
    end

end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :student
  

  def to_s  
    student.last_name + " payment of #{amount} on " + payment_date.strftime("%m/%d/%Y")
  end
  
end

app/models/routine.rb
class Routine < ApplicationRecord
  belongs_to :student
end

app/models/student.rb
class Student < ApplicationRecord
    has_many :packages
    has_many :routines
    def to_s
     return self.first_name + " " + self.last_name
    end
    
    def lessons_remaining
        @lessons = 0
        self.packages.each do |p|
            @lessons += p.remaining
        end
        return @lessons
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :set_payment, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, :ensure_admin!
  
  # GET /payments
  # GET /payments.json
  def index
    @payments = Payment.all.order(payment_date: :desc)
  end

  # GET /payments/1
  # GET /payments/1.json
  def show
  end

  # GET /payments/new
  def new
    @payment = Payment.new
  end

  # GET /payments/1/edit
  def edit
  end

  # POST /payments
  # POST /payments.json
  def create
    @payment = Payment.new(payment_params)

    respond_to do |format|
      if @payment.save
        format.html { redirect_to @payment, notice: 'Payment was successfully created.' }
        format.json { render :show, status: :created, location: @payment }
      else
        format.html { render :new }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /payments/1
  # PATCH/PUT /payments/1.json
  def update
    respond_to do |format|
      if @payment.update(payment_params)
        format.html { redirect_to @payment, notice: 'Payment was successfully updated.' }
        format.json { render :show, status: :ok, location: @payment }
      else
        format.html { render :edit }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payments/1
  # DELETE /payments/1.json
  def destroy
    @payment.destroy
    respond_to do |format|
      format.html { redirect_to payments_url, notice: 'Payment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_payment
      @payment = Payment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def payment_params
      params.require(:payment).permit(:student_id, :payment_date, :payment_type, :description, :amount, :account)
    end
    
    def ensure_admin!
      unless current_user.admin?
        flash[:notice] = 'Sorry, you have to have admin privileges to see this page.'
      redirect_to root_path
      return false
      end
    end
end

app/helpers/calendar_helper.rb
module CalendarHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/dances_helper.rb
module DancesHelper
end

app/helpers/figures_helper.rb
module FiguresHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/levels_helper.rb
module LevelsHelper
end

app/helpers/packages_helper.rb
module PackagesHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/routines_helper.rb
module RoutinesHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/payments/_form.html.erb
<%= form_with(model: payment, local: true, :class => "ui form") do |form| %>
  <% if payment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(payment.errors.count, "error") %> prohibited this payment from being saved:</h2>

      <ul>
      <% payment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :student_id, "Student" %>
        <%= form.collection_select(:student_id, Student.all.order('last_name'), :id, :last_name, {:prompt => true}, {:class => "search dropdown"}) %>
  </div>

  <div class="field">
    <%= form.label :payment_date, "Payment Date" %>
    <%= form.text_field :payment_date, :id => "dateTime" %>
  </div>

  <div class="field inline fields">
    <%= form.label :payment_type, "Payment Type" %>
    <%= form.radio_button :payment_type, 'Cash', :class => "ui radio checkbox"  %>
    <%= form.label :payment_type_cash, 'Cash' %>
    <%= form.radio_button :payment_type, 'Cheque', :class => "ui radio checkbox"  %>
    <%= form.label :payment_type_cheque, 'Cheque' %>
    <%= form.radio_button :payment_type, 'Transfer', :class => "ui radio checkbox"  %>
    <%= form.label :payment_type_transfer, 'Transfer' %>
    <%= form.radio_button :payment_type, 'Credit', :class => "ui radio checkbox"  %>
    <%= form.label :payment_type_credig, 'Credit Card' %>
  </div>

  <div class="field">
    <%= form.label :amount %>
    <%= form.text_field :amount %>
  </div>

    <div class="field inline fields">
    <%= form.label :account, "Into Account" %>
    <%= form.radio_button :account, 'IOU', :class => "ui radio checkbox"  %>
    <%= form.label :account_iou, 'IOU' %>
    <%= form.radio_button :account, 'Cash on Hand', :class => "ui radio checkbox"  %>
    <%= form.label :account_cash, 'Cash On Hand' %>
    <%= form.radio_button :account, 'Chequing Account', :class => "ui radio checkbox"  %>
    <%= form.label :account_chequing, 'Chequing Account' %>
  </div>
    <div class="field">
    <%= form.label :description, 'Description' %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit :class => "ui button" %>
  </div>
<% end %>

app/views/payments/edit.html.erb
<h1>Editing Payment</h1>

<%= render 'form', payment: @payment %>

<%= link_to 'Show', @payment %> |
<%= link_to 'Back', payments_path %>

app/views/payments/index.html.erb
<h1>Payments</h1>

<%= link_to 'New Payment', new_payment_path, :class => "ui button" %>
<table class="ui sortable unstackable table">
  <thead>
    <tr>
      <th>ID</th>
      <th>Student</th>
      <th>Payment date</th>
      <th>Payment type</th>
      <th>Amount</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @payments.each do |payment| %>
      <tr>
        <td><%= payment.id %></td>
        <td><%= payment.student.last_name %></td>
        <td><%= I18n.l payment.payment_date, format: :long %></td>
        <td><%= payment.payment_type %></td>
        <td><%= number_to_currency payment.amount %></td>
        <td><%= payment.description %></td>
        <td><%= link_to 'Show', payment %></td>
        <td><%= link_to 'Edit', edit_payment_path(payment) %></td>
        <td><%= link_to 'Destroy', payment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/payments/new.html.erb
<h1>New Payment</h1>

<%= render 'form', payment: @payment %>

<%= link_to 'Back', payments_path %>

app/views/payments/show.html.erb
<div class="ui card fluid">
  <div class="content">
    <div class="header center aligned"><h2><%= @payment.student.last_name %> - #<%= @payment.id %></h2></div>
    <div class="meta"><h4><%= @payment.payment_date %></h4></div>
    <div class="description">
         <h2 class="centered">Details</h2>
<h3>Type: <%= @payment.payment_type %></h3>
<h3>Amount:  <%= number_to_currency @payment.amount %></h3>
<h3>Account: <%= @payment.account %></h3>
    </div>
  </div>
  <div class="extra content">
    
  </div>
</div> 
  


<%= link_to 'Edit', edit_payment_path(@payment) %> |
<%= link_to 'Back', payments_path %>