config/routes.rb
Rails.application.routes.draw do
  resources :figures
  resources :dances
  resources :categories
  resources :levels
  resources :routines
  resources :packages
  resources :payments
  resources :lessons
  resources :calendar
  resources :students
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "backup", to: "welcome#backup"
  root 'welcome#index'
end

app/models/category.rb
class Category < ApplicationRecord

    def to_s
    return self.title
    end
end

app/models/dance.rb
class Dance < ApplicationRecord
  belongs_to :category
    def to_s
        return "#{self.category} #{self.title}"
    end
end

app/models/figure.rb
class Figure < ApplicationRecord
  belongs_to :level
  belongs_to :dance
  
  def to_s
    return self.title
  end
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :student
  has_one :package
  has_one :payment
  before_save :set_status
  validates :start_time, presence: true
  scope :this_years_lessons, -> { where('start_time > ?', Date.current.beginning_of_year) }
  
  def end_date
        self.start_time  + 60*60
  end
  
  def to_s
    self.student.last_name + " - " + self.start_time.to_formatted_s(:long)
  end
  
private
  def set_status
    if self.plan.present?
    self.is_planned = true
else
    self.is_planned = false
    end
    if self.payment_id || self.package_id
        self.is_paid = true
    else
        self.is_paid = false
    end
  end
end

app/models/level.rb
class Level < ApplicationRecord
    def to_s
        return self.title
    end
end

app/models/package.rb
class Package < ApplicationRecord
  belongs_to :student
  belongs_to :payment
  has_many :lessons, dependent: :destroy
  enum status: [ :active, :inactive ]
  after_find :set_activity
  
  def remaining
   return self.lessons_purchased - self.lessons.count
  end
  
  def to_s
   self.student.last_name + " payment with ID of #{self.payment_id} on " + self.payment.payment_date.strftime("%A, %b. %d") 
  end

    def set_activity
    if self.lessons_purchased > self.lessons.count
        self.active!
     else
         self.inactive!
    end
    end

end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :student
  

  def to_s  
    student.last_name + " payment of #{amount} on " + payment_date.strftime("%m/%d/%Y")
  end
  
end

app/models/routine.rb
class Routine < ApplicationRecord
  belongs_to :student
end

app/models/student.rb
class Student < ApplicationRecord
    has_many :packages
    has_many :routines
    def to_s
     return self.first_name + " " + self.last_name
    end
    
    def lessons_remaining
        @lessons = 0
        self.packages.each do |p|
            @lessons += p.remaining
        end
        return @lessons
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/helpers/calendar_helper.rb
module CalendarHelper
end

app/helpers/dances_helper.rb
module DancesHelper
end

app/helpers/figures_helper.rb
module FiguresHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/levels_helper.rb
module LevelsHelper
end

app/helpers/packages_helper.rb
module PackagesHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/routines_helper.rb
module RoutinesHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/partials/_admin_menu.html.erb
<div class="ui top twelve item attached menu">
  
   <%= link_to "Dashboard", root_path, class: "item" %> 
         <%= link_to "Lessons", lessons_path, class: "item" %>
         <%= link_to "Students", students_path, class: "item" %>
         <%= link_to "Payments", payments_path, class: "item" %>
         <%= link_to "Packages", packages_path, class: "item" %>
          <%= link_to "Routines", routines_path, class: "item" %>
     <% if user_signed_in? %>
      <%= link_to('Logout', destroy_user_session_path, method: :delete, class: "item") %>
      <% else %>
      <%= link_to('Login', new_user_session_path, class: "item")  %>
      <% end %>
       <div class="ui simple dropdown item">
    Syllabus Admin
    <i class="dropdown icon"></i>
    <div class="menu">
      <%= link_to "Levels", levels_path, class: "item" %>
     <%= link_to "Categories", categories_path, class: "item" %>
     <%= link_to "Dances", dances_path, class: "item" %>
     <%= link_to "Figures", figures_path, class: "item" %>
    </div>
  </div>
</div>
      

app/views/layouts/partials/_main_menu.html.erb
  <div class="">

      <%= link_to "Dashboard", root_path, class: "item" %>

              <% if user_signed_in? %>
                <%= link_to('Logout', destroy_user_session_path, method: :delete, class: "item") %>
                  <% else %>
                    <%= link_to('Login', new_user_session_path, class: "item")  %>
                      <% end %>
    </div>

app/views/layouts/partials/_sidebar.html.erb
        <%= link_to "Dashboard", root_path, class: "item" %> 
         <%= link_to "Lessons", lessons_path, class: "item" %>
         <%= link_to "Students", students_path, class: "item" %>
         <%= link_to "Payments", payments_path, class: "item" %>
         <%= link_to "Packages", packages_path, class: "item" %>
          <%= link_to "Routines", routines_path, class: "item" %>
     <% if user_signed_in? %>
      <%= link_to('Logout', destroy_user_session_path, method: :delete, class: "item") %>
      <% else %>
      <%= link_to('Login', new_user_session_path, class: "item")  %>
      <% end %>
      